server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      generate-ddl: true

logging:
  level:
    root: INFO
    org.springframework.security: ERROR
    org.springframework: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: WARN
    org.hibernate.validator.internal.engine.ValidatorImpl: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.SQL: INFO
    com.amwebexpert: DEBUG
